language: python
python:
  - "3.8"
  - "3.9"
  # - "3.10" # Travis fails to install Python 3.10
  - "nightly"  # nightly build

before_install:
  - pip install codecov

after_success:
  - codecov

install:
  - pip install -r requirements.txt

script:
  - pre-commit run --all-files
  - pytest src/djangostatuspage/tests --cov-report xml
