# Generated by Django 3.2.10 on 2021-12-15 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, max_length=32, null=True)),
                ('id_at_origin', models.CharField(max_length=255)),
                ('technical_details', models.TextField(blank=True, default='', null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_created_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
