# Generated by Django 3.2.10 on 2021-12-16 20:23

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, choices=[('manual', 'Manual')], max_length=32, null=True)),
                ('id_at_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_created_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_category_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_category_created_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_category_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'system categories',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('alias', models.CharField(max_length=128, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangostatuspage.systemcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_created_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_update_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('technical_details', models.TextField(blank=True, default='', null=True)),
                ('severity', models.TextField(choices=[('critical', 'Critical'), ('error', 'Error'), ('warning', 'Warning'), ('information', 'Informational'), ('verbose', 'Verbose')], max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('ack', 'Acknowledged'), ('closed', 'Closed')], max_length=32)),
                ('monitor_status', models.CharField(choices=[('fired', 'Fired'), ('resolved', 'Resolved')], max_length=32)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('effective_until', models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0, tzinfo=utc))),
                ('affected_system', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangostatuspage.system')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_update_created_set', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangostatuspage.incident')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_update_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
