# Generated by Django 3.2.10 on 2021-12-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangostatuspage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcategory',
            name='system_category_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.CreateModel(
            name='StatusPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_page_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_page_created_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_page_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
