# Generated by Django 3.2.10 on 2021-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangostatuspage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='id_at_origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
