# Generated by Django 3.2.10 on 2021-12-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangostatuspage', '0005_alter_incident_affected_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ('rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='systemcategory',
            options={'ordering': ('rank', 'name')},
        ),
        migrations.AddField(
            model_name='system',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemcategory',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
