# Generated by Django 3.2.10 on 2021-12-15 19:02

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangostatuspage', '0006_auto_20211215_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemcategory',
            options={'verbose_name_plural': 'system categories'},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='affected_system',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='technical_details',
        ),
        migrations.AlterField(
            model_name='system',
            name='system_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='systemcategory',
            name='system_category_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_update_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('technical_details', models.TextField(blank=True, default='', null=True)),
                ('severity', models.TextField(choices=[('critical', 'Critical'), ('error', 'Error'), ('warning', 'Warning'), ('information', 'Informational'), ('verbose', 'Verbose')], max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('ack', 'Acknowledged'), ('closed', 'Closed')], max_length=32)),
                ('monitor_status', models.CharField(choices=[('fired', 'Fired'), ('resolved', 'Resolved')], max_length=32)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('effective_until', models.DateTimeField(default=datetime.datetime(2021, 12, 15, 19, 2, 4, 328541, tzinfo=utc))),
                ('affected_system', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangostatuspage.system')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_update_created_set', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangostatuspage.incident')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_update_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
