# Generated by Django 3.2.10 on 2021-12-15 19:03

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangostatuspage', '0007_auto_20211215_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentupdate',
            name='effective_until',
            field=models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
