# Generated by Django 3.2.10 on 2021-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangostatuspage', '0008_alter_incidentupdate_effective_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
